<?php
return [
    '➡️Нажмите здесь👍⬅️' => \App\Commands\AskBirthday::class,
    'Ввести дату рождения🎁' => \App\Commands\AskBirthday::class,
    'Главное меню ✅' => \App\Commands\MainMenu::class,
    'Пропустить➡' => \App\Commands\MainMenu::class,
    'Связаться с нами' => \App\Commands\Contacts::class,
    'Как доехать 🏁' => \App\Commands\Address::class,
    'Общественный транспорт 🚃' => \App\Commands\Address::class,
    'Авто🚖🚘' => \App\Commands\Address::class,
    'Часто задаваемые вопросы' => \App\Commands\FAQ::class,
    'О враче' => \App\Commands\AboutDoctor::class,
    'Список услуг' => \App\Commands\ServiceList::class,
    'Записаться на прием🗓🖊' => \App\Commands\OfferAppointment::class,
    'Отмена' => \App\Commands\MainMenu::class,
    'Посмотреть другие дни недели⬇' => \App\Commands\OfferAppointment::class,
    'Посмотреть другие дни недели' => \App\Commands\AdminOfferAppointment::class,
    '🧑 Профиль' => \App\Commands\Profile::class,
    'изменить ФИО' => \App\Commands\Profile::class,
    'изменить номер телефона 📲' => \App\Commands\Profile::class,
    'Мои записи' => \App\Commands\MyRecords::class,
    'Отписаться от рассылки' => \App\Commands\UnSetNotif::class,
    'создать запись' => \App\Commands\AdminOfferAppointment::class,
    'статистика рассылок' => \App\Commands\AdminUserStat::class,
    'отменить запись' => \App\Commands\AdminRecords::class,
];
